// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import Head from 'next/head';
import client from 'lib/sitecore-client';
import { useCallback, useRef, useState, useEffect, useMemo } from 'react';
import React from 'react';
import { Placeholder, RichText, NextImage, Link, Text, useSitecore, withDatasourceCheck, CdpHelper, Image as Image_8a80e63291fea86e0744df19113dc44bec187216 } from '@sitecore-content-sdk/nextjs';
import PreviewSearchWidget from 'src/components/Search/PreviewSearch/PreviewSearch';
import { isSearchSDKEnabled } from 'src/services/SearchSDKService';
import PreviewSearchIcon from 'src/components/Search/PreviewSearch/PreviewSearchIcon';
import ClickOutside from 'src/hooks/ClickOutside';
import { useRouter } from 'next/router';
import Image from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';
import { useI18n } from 'next-localization';
import { Presence, ArticleCard, PreviewSearch } from '@sitecore-search/ui';
import { FilterEqual, WidgetDataType, usePreviewSearch, widget, PageController } from '@sitecore-search/react';
import Spinner from 'src/components/Search/components/Spinner/Spinner';
import useVisibility from 'src/hooks/useVisibility';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Autoplay, EffectCoverflow, Pagination, Navigation } from 'swiper/modules';
import { CountUp } from 'components/NonSitecore/CountUp';
import { DottedAccent } from 'components/NonSitecore/DottedAccent';
import { ParallaxBackgroundImage } from 'components/NonSitecore/ParallaxBackgroundImage';
import Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 from 'next/link';
import { FacebookIcon, FacebookShareButton, LinkedinIcon, LinkedinShareButton, TwitterIcon, TwitterShareButton } from 'react-share';
import { ParallaxBanner, useParallax, Parallax } from 'react-scroll-parallax';
import { IconAccent } from 'components/NonSitecore/IconAccent';

const importMap = [
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useCallback', value: useCallback },
      { name: 'useRef', value: useRef },
      { name: 'useState', value: useState },
      { name: 'useEffect', value: useEffect },
      { name: 'useMemo', value: useMemo },
      { name: 'default', value: React },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Placeholder', value: Placeholder },
      { name: 'RichText', value: RichText },
      { name: 'NextImage', value: NextImage },
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'Image', value: Image_8a80e63291fea86e0744df19113dc44bec187216 },
    ]
  },
  {
    module: 'src/components/Search/PreviewSearch/PreviewSearch',
    exports: [
      { name: 'default', value: PreviewSearchWidget },
    ]
  },
  {
    module: 'src/services/SearchSDKService',
    exports: [
      { name: 'isSearchSDKEnabled', value: isSearchSDKEnabled },
    ]
  },
  {
    module: 'src/components/Search/PreviewSearch/PreviewSearchIcon',
    exports: [
      { name: 'default', value: PreviewSearchIcon },
    ]
  },
  {
    module: 'src/hooks/ClickOutside',
    exports: [
      { name: 'default', value: ClickOutside },
    ]
  },
  {
    module: 'next/router',
    exports: [
      { name: 'useRouter', value: useRouter },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: 'next-localization',
    exports: [
      { name: 'useI18n', value: useI18n },
    ]
  },
  {
    module: '@sitecore-search/ui',
    exports: [
      { name: 'Presence', value: Presence },
      { name: 'ArticleCard', value: ArticleCard },
      { name: 'PreviewSearch', value: PreviewSearch },
    ]
  },
  {
    module: '@sitecore-search/react',
    exports: [
      { name: 'FilterEqual', value: FilterEqual },
      { name: 'WidgetDataType', value: WidgetDataType },
      { name: 'usePreviewSearch', value: usePreviewSearch },
      { name: 'widget', value: widget },
      { name: 'PageController', value: PageController },
    ]
  },
  {
    module: 'src/components/Search/components/Spinner/Spinner',
    exports: [
      { name: 'default', value: Spinner },
    ]
  },
  {
    module: 'src/hooks/useVisibility',
    exports: [
      { name: 'default', value: useVisibility },
    ]
  },
  {
    module: 'swiper/react',
    exports: [
      { name: 'Swiper', value: Swiper },
      { name: 'SwiperSlide', value: SwiperSlide },
    ]
  },
  {
    module: 'swiper/modules',
    exports: [
      { name: 'Autoplay', value: Autoplay },
      { name: 'EffectCoverflow', value: EffectCoverflow },
      { name: 'Pagination', value: Pagination },
      { name: 'Navigation', value: Navigation },
    ]
  },
  {
    module: 'components/NonSitecore/CountUp',
    exports: [
      { name: 'CountUp', value: CountUp },
    ]
  },
  {
    module: 'components/NonSitecore/DottedAccent',
    exports: [
      { name: 'DottedAccent', value: DottedAccent },
    ]
  },
  {
    module: 'components/NonSitecore/ParallaxBackgroundImage',
    exports: [
      { name: 'ParallaxBackgroundImage', value: ParallaxBackgroundImage },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 },
    ]
  },
  {
    module: 'react-share',
    exports: [
      { name: 'FacebookIcon', value: FacebookIcon },
      { name: 'FacebookShareButton', value: FacebookShareButton },
      { name: 'LinkedinIcon', value: LinkedinIcon },
      { name: 'LinkedinShareButton', value: LinkedinShareButton },
      { name: 'TwitterIcon', value: TwitterIcon },
      { name: 'TwitterShareButton', value: TwitterShareButton },
    ]
  },
  {
    module: 'react-scroll-parallax',
    exports: [
      { name: 'ParallaxBanner', value: ParallaxBanner },
      { name: 'useParallax', value: useParallax },
      { name: 'Parallax', value: Parallax },
    ]
  },
  {
    module: 'components/NonSitecore/IconAccent',
    exports: [
      { name: 'IconAccent', value: IconAccent },
    ]
  }
];

export default combineImportEntries(defaultImportEntries, importMap);
